### ISSUE TITLE
Link to Shortcuts script just links to Apple Store

### ISSUE THREAD

**Issue by brandonhaslegs** [PsiPhiTheta/GoogleMaps-2-AppleMaps#3] opened 2022-05-17 13:42 UTC
Clicking "Get shortcut" from this page https://www.icloud.com/shortcuts/b70812c989a148d084b070ef4772988e just takes me to the iOS Shortcuts App download page.

**Comment by brandonhaslegs** [comment] 2022-05-17 13:47
You should make it clear you need to open this link on your iPhone, you can't open it on your Mac.

**Comment by PsiPhiTheta** [comment] 2022-05-17 19:11
Dupe of #1

**Closed** 2022-05-17 19:11 UTC
